### ISSUE TITLE
[BUG] Microbot Agility Plugin Fails at Seers

### ISSUE THREAD

**Issue by Jrod7938** [chsami/Microbot#19]
### Type

Incorrect behavior

### Operating System

None

### OS Version

Windows & MacOS Sonoma

### Bug description

Starting the plugin in Seers village causes the error in the photo. Might be a result of the agility obstacles being smaller than 1x1 so menu swapper can't click it?

### Screenshots or videos

<img width="1630" alt="Screenshot 2023-08-23 at 5 23 43 PM" src="https://github.com/chsami/microbot/assets/46418742/4ffe49e3-5fff-40ac-ae1e-d8eb5edb7719">

### RuneLite version

Microbot Version 1.10.11

### Logs

java.lang.ClassCastException: class jw cannot be cast to class net.runelite.api.GameObject (jw is in unnamed module of loader net.runelite.client.rs.ClientLoader$1 @29e7f91a; net.runelite.api.GameObject is in unnamed module of loader 'app')
	at net.runelite.client.plugins.microbot.util.gameobject.Rs2GameObject.handleMenuSwapper(Rs2GameObject.java:594)
	at net.runelite.client.plugins.microbot.MicrobotPlugin.onMenuEntryAdded(MicrobotPlugin.java:133)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:193)
	at client.gu(client.java:8385)
	at ne.kz(ne.java:9207)
	at client.mb(client.java:3022)
	at client.bs(client.java:1162)
	at bm.ay(bm.java:401)
	at bm.run(bm.java:380)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-08-23 17:22:53 EDT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.ClassCastException: class jw cannot be cast to class net.runelite.api.GameObject (jw is in unnamed module of loader net.runelite.client.rs.ClientLoader$1 @29e7f91a; net.runelite.api.GameObject is in unnamed module of loader 'app')
	at net.runelite.client.plugins.microbot.util.gameobject.Rs2GameObject.handleMenuSwapper(Rs2GameObject.java:594)
	at net.runelite.client.plugins.microbot.MicrobotPlugin.onMenuEntryAdded(MicrobotPlugin.java:133)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:193)
	at client.gu(client.java:8385)
	at eb.lk(eb.java:10237)
	at ov.lg(ov.java:10223)
	at fe.lc(fv.java:10249)
	at af.ml(af.java:11555)
	at af.ml(af.java:11912)
	at af.ml(af.java:11912)
	at af.ml(af.java:11912)
	at db.mf(db.java:11423)
	at client.mb(client.java:3311)
	at client.bs(client.java:1162)
	at bm.ay(bm.java:401)
	at bm.run(bm.java:380)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by chsami** [comment]
This has been fixed in the following commit:

https://github.com/chsami/microbot/commit/4f5336283d8149382d9a3b99ba83a9796ac184e6

**Comment by chsami** [comment]
This has been fixed in the following commit: https://github.com/chsami/microbot/commit/4f5336283d8149382d9a3b99ba83a9796ac184e6
